service: boilerplate-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev

functions:
  houses:
    handler: src/handlers/houses.handler
    events:
      - http:
          method: get
          path: houses
          integration: lambda
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
