service: boilerplate-service

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: GET
          path: hello
          cors: true

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
